### PR TITLE
Working on Albanian Holidays

### PR DESCRIPTION
**Pull request by OrgesKreka**
- Fix some holidays for Albania
- Add test for Albania

### CODE REVIEW

**Comment by tinohager** [comment]
please not remove the `HolidaySpecification` i would like it to be consistent across all providers

**Comment by OrgesKreka** [comment]
> please not remove the `HolidaySpecification` i would like it to be consistent across all providers

@tinohager Done.

Also I was thinking for a naive implementation of IMuslimProvider, that checks if you are online and scraps the dates ( at least for ul-Fitr and ul-Adha ) from Wikipedia. If there is no internet connection it will behave as it is now.

Let me know what do you think?

**Comment by tinohager** [comment]
I think that companies that use this package do not want a connection to be suddenly established from their network to the Internet. I see the problem for these holidays but I don't want to implement an online connection to a third party service.

**Comment by tinohager** [comment]
You can easily see what changes your PR triggers via the 'Files changed' tab. Please use this to check the changes.

**Comment by OrgesKreka** [comment]
> I think that companies that use this package do not want a connection to be suddenly established from their network to the Internet. I see the problem for these holidays but I don't want to implement an online connection to a third party service.

I see, then what do you think it should be the best approach to handle this? 
I see the implementation of the Turkey Holidays but someone reported that those dates are wrongly.

**Comment by OrgesKreka** [comment]
> You can easily see what changes your PR triggers via the 'Files changed' tab. Please use this to check the changes.

Yes, i brought back the initializer of HolidaySpecification.

**Comment by tinohager** [comment]
> > You can easily see what changes your PR triggers via the 'Files changed' tab. Please use this to check the changes.
> 
> Yes, i brought back the initializer of HolidaySpecification.

image

**Comment by tinohager** [comment]
> > I think that companies that use this package do not want a connection to be suddenly established from their network to the Internet. I see the problem for these holidays but I don't want to implement an online connection to a third party service.
> 
> I see, then what do you think it should be the best approach to handle this? I see the implementation of the Turkey Holidays but someone reported that those dates are wrongly.

- The public holidays are entered when they become known and there is a static implementation. This must be maintained annually.
- Holidays are defined which meet the time range but are marked as optional. With the information that this is an area that cannot be calculated.
- The public holidays are completely removed from Nager.Date.

**Comment by OrgesKreka** [comment]
> > > You can easily see what changes your PR triggers via the 'Files changed' tab. Please use this to check the changes.
> > 
> > 
> > Yes, i brought back the initializer of HolidaySpecification.
> 
> image

Sorry about that.
Can you please check now.

**Comment by OrgesKreka** [comment]
> > > I think that companies that use this package do not want a connection to be suddenly established from their network to the Internet. I see the problem for these holidays but I don't want to implement an online connection to a third party service.
> > 
> > 
> > I see, then what do you think it should be the best approach to handle this? I see the implementation of the Turkey Holidays but someone reported that those dates are wrongly.
> 
> * The public holidays are entered when they become known and there is a static implementation. This must be maintained annually.
> * Holidays are defined which meet the time range but are marked as optional. With the information that this is an area that cannot be calculated.
> * The public holidays are completely removed from Nager.Date.

I see.
If you need any help on implementing it. Just reach me out.

Thanks!

**Comment by tinohager** [comment]
I have checked the date changes they look good. I would adopt them straight away. We should still revise the unit test logic. Please do not delete any commented out code. We have just completely restructured the library and I would like to remove the old code all together. It helps us to check what has changed in current issues.

**Comment by tinohager** [comment]
image

**Comment by OrgesKreka** [comment]
> image

check now.

**Review by tinohager — APPROVED** [review]

**Comment by tinohager** [comment]
@OrgesKreka many thanks for your help

**Pull request merged**
