### PR TITLE
Update New Zealand Provider

### PR DESCRIPTION
**Pull request by nick-goloborodko**
Update New Zealand provider to fix the Regional Holiday issue where Manawatu-Wanganui and Hawke's Bay were included twice: once on their correct regional dates, and once (incorrectly) in Auckland/Northland Anniversary Day. For reference: https://www.govt.nz/browse/work/public-holidays-and-work/public-holidays-and-anniversary-dates/

### CODE REVIEW

**Comment by tinohager** [comment]
Hi i search some source for the update, in this documentation i can found nothing
https://www.legislation.govt.nz/act/public/2003/0129/latest/DLM236387.html

**Comment by tinohager** [comment]
I have send a query to employment.govt.nz

**Comment by tinohager** [comment]
@nick-goloborodko have you some official sources for me?

**Review by DigitalCare-MarcinGozdziewski — APPROVED** [review]

**Review by tinohager — COMMENTED** [review]
No official sources found. The creator of the PR lives in Auckland so we will use his statement.

**Review by tinohager — APPROVED** [review]

**Pull request closed without merging**
