### PR TITLE
Added missing holidays to Andorra (wikipedia source)

### PR DESCRIPTION
**Pull request by askelia**
Except Carnaval (date unknown)
Corrected National Holiday date

### CODE REVIEW

**Review by tinohager — APPROVED** [review]

**Comment by tinohager** [comment]
The code have some syntax failures

For Carnival you can check this
```cs
            items.Add(new PublicHoliday(easterSunday.AddDays(-48), "Carnaval", "Carnival", countryCode));
            items.Add(new PublicHoliday(easterSunday.AddDays(-47), "Carnaval", "Carnival", countryCode));
```

```cs
using Nager.Date.Contract;
using Nager.Date.Model;
using System.Collections.Generic;
using System.Linq;

namespace Nager.Date.PublicHolidays
{
    /// <summary>
    /// Andorra
    /// </summary>
    public class AndorraProvider : IPublicHolidayProvider
    {
        private readonly ICatholicProvider _catholicProvider;

        /// <summary>
        /// AndorraProvider
        /// </summary>
        /// <param name="catholicProvider"></param>
        public AndorraProvider(ICatholicProvider catholicProvider)
        {
            this._catholicProvider = catholicProvider;
        }

        ///<inheritdoc/>
        public IEnumerable<PublicHoliday> Get(int year)
        {
            var countryCode = CountryCode.AD;

            var items = new List<PublicHoliday>();
            items.Add(new PublicHoliday(year, 1, 1, "Any nou", "New Year's Day", countryCode));
            items.Add(new PublicHoliday(year, 1, 6, "Reis", "Epiphany", countryCode));
            ///TODO: Carnaval is not implemented : how to find the date ? 
            items.Add(new PublicHoliday(year, 3, 14, "Dia de la Constitució", "Constitution Day", countryCode));
            items.Add(this._catholicProvider.GoodFriday("Divendres Sant", year, countryCode));
            items.Add(this._catholicProvider.EasterMonday("Dilluns de Pasqua", year, countryCode));        
            items.Add(new PublicHoliday(year, 5, 1, "Festa del Treball", "Labour Day", countryCode));
            items.Add(this._catholicProvider.WhitMonday("Dilluns de Pentecosta", year, countryCode));
            items.Add(new PublicHoliday(year, 8, 15, "Assumpció", "Assumption Day", countryCode));
            items.Add(new PublicHoliday(year, 9, 8, "Mare de Déu de Meritxell", "National Holiday", countryCode));
            items.Add(new PublicHoliday(year, 11, 1, "Tots Sants", "All Saints' Day", countryCode));
            items.Add(new PublicHoliday(year, 12, 8, "Immaculada Concepció", "Immaculate Conception", countryCode));
            items.Add(new PublicHoliday(year, 12, 25, "Nadal", "Christmas Day", countryCode));
            items.Add(new PublicHoliday(year, 12, 26, "Sant Esteve", "St. Stephen's Day", countryCode));

            return items.OrderBy(o => o.Date);
        }

        ///<inheritdoc/>
        public IEnumerable<string> GetSources()
        {
            return new string[]
            {
                "https://en.wikipedia.org/wiki/Public_holidays_in_Andorra"
            };
        }
    }
}
```

**Comment by askelia** [comment]
> The code have some syntax failures
> 
> For Carnival you can check this
> 
> ```cs
> items.Add(new PublicHoliday(easterSunday.AddDays(-48), "Carnaval", "Carnival", countryCode));
> items.Add(new PublicHoliday(easterSunday.AddDays(-47), "Carnaval", "Carnival", countryCode));
> ```


Hi,
sorry for the syntax errors, it's my first c# code and my 1st github contributions.

For Carnival dates do you have a source ? 
According to those sites https://publicholidays.eu/andorra/carnival/ or https://andorrapartner.com/public-holidays/ Id' say -48 is correct since it's a monday, but -47 leads to a tuesday which is not referenced as being a holiday.


Thanks

**Review by tinohager — APPROVED** [review]

**Comment by tinohager** [comment]
@askelia can you fix the conflicts i have no write access to this PR

**Comment by tinohager** [comment]
@askelia Many thanks for the improvements

**Comment by askelia** [comment]
Thanks for your work, and for being patient despite of my mistakes, I should get better at it for next PR (there should be more).

**Pull request merged**
