### PR TITLE
Add IsPublicHoliday(DateTime date, string countryCode) to DateSystem.cs

### LINKED ISSUE #195: Feature: IsPublicHoliday using string countryCode
### Important specifications

* Which country is affected? All

For more information, see the `CONTRIBUTING` guide.

### Description

Most methods in DateSystem.cs has two overloads, one taking a string countryCode and one taking a CountryCode enum. IsPublicHoliday does not have this. I need that instead of my code having to parse the enum :)

### PR DESCRIPTION
**Pull request by CasperWSchmidt**
Closes #195

### CODE REVIEW

**Comment by tinohager** [comment]
@CasperWSchmidt can you please customize all Enum.TryParse with the ArgumentException. So that we have a consistent behavior

**Comment by CasperWSchmidt** [comment]
@tinohager Will do, but in some cases I believe it also makes sense to simply return null.

Also I stumbled upon https://josef.codes/beware-of-enum-try-parse/ so I included an Enum.IsDefined check.

**Comment by CasperWSchmidt** [comment]
@tinohager perhaps all the CountryCode-enums should have a specific int value? IDK if all countries have an official number, but if they do, it would be obvious to select that as the int value for the enums :)

**Comment by tinohager** [comment]
What improvements do you see in the use of Enum.IsDefined if we only use strings?

**Comment by CasperWSchmidt** [comment]
@tinohager You/We can't control the string users send as argument. This means someone can use "1000" if they want to. This will result in a CountryCode enum with an undefined value being used in the rest of the code with unknown consequences.

**Comment by tinohager** [comment]
`IsDefined` does not behave the same for 'de' or 'DE

**Comment by CasperWSchmidt** [comment]
@tinohager Sorry about that. Changed the Enum.IsDefined to use the output from TryParse. This works according to [this](https://stackoverflow.com/questions/3157936/how-can-i-test-if-an-enum-is-defined-or-not-whilst-ignoring-case). Also added unit tests to validate that the changes are indeed behaving the same for "DE" and "de" now.

**Comment by tinohager** [comment]
@CasperWSchmidt Thanks

**Pull request merged**
