### PR TITLE
Hong Kong - Add Provider

### PR DESCRIPTION
**Pull request by tinohager**
https://github.com/nager/Nager.Date/issues/258
https://github.com/nager/Nager.Date/issues/156

### CODE REVIEW

**Comment by tinohager** [comment]
Open Issues:
According to Hong Kong laws, when a designated public holiday falls on a Sunday or on the same day of another holiday, the immediate following weekday would be a public holiday. However, there are exceptions; for example, as Lunar New Year 2007 falls on a Sunday (18 February), the government have designated the Saturday directly before (17 February) as a public holiday.[2] However, this does not apply to Saturdays, and when a non-statutory public holiday falls on a Saturday, the public holiday is lost to people that do not work on Saturdays.

**Review by samtrion — APPROVED** [review]

**Comment by samtrion** [comment]
@tinohager Is here anything open? or can we merge

**Comment by tinohager** [comment]
@samtrion Yes the sunday or day of another holiday move is open.

**Comment by YipingRuan** [comment]
> Open Issues:
> According to Hong Kong laws, when a designated public holiday falls on a Sunday or on the same day of another holiday, the immediate following weekday would be a public holiday. However, there are exceptions; for example, as Lunar New Year 2007 falls on a Sunday (18 February), the government have designated the Saturday directly before (17 February) as a public holiday.[2] However, this does not apply to Saturdays, and when a non-statutory public holiday falls on a Saturday, the public holiday is lost to people that do not work on Saturdays.

Can you comment on similar cases for Singapore?

image

**Comment by tinohager** [comment]
open a new PR

**Pull request closed without merging**
